### ISSUE TITLE
和原生的 JSONEncoder 和 JSONDecoder 有啥区别 有性能对比吗？

### ISSUE THREAD

**Issue by josercc** [kakaopensource/KakaJSON#10]

**Comment by kinarobin** [comment]
@josercc 


![Model](https://img2018.cnblogs.com/blog/497279/201908/497279-20190818113355045-41212639.png)
![Codable](https://img2018.cnblogs.com/blog/497279/201908/497279-20190818113404897-1905468755.png)
![KakaJson](https://img2018.cnblogs.com/blog/497279/201908/497279-20190818113415672-1866782244.png)

**Comment by josercc** [comment]
@kinarobin 很棒

**Comment by CoderMJLee** [comment]
建议有空可以看看中文教程哈，有很多Codale不太能轻易实现的细节，都已经封装好了
