### ISSUE TITLE
关于 struct 的使用

### ISSUE THREAD

**Issue by MuRanJiangXia** [kakaopensource/KakaJSON#11]
struct Cat: Convertible  {

        var name: String?
        var weight: Double?
    }

这样是可行的 

    struct Cat: Convertible  {
        
        init() {
            name = "cyan"
        }

        let name: String?
        var weight: Double?
    }

属性 有let的情况 为什么要加个   init()？

**Comment by CoderMJLee** [comment]
这是Swift语法相关的问题，要求let在对象初始化完之前必须要有初始值，你这样写就好了
```swift
struct Cat: Convertible  {
    let name: String? = nil
    var weight: Double?
}
```

**Comment by MuRanJiangXia** [comment]
好的 谢谢~
