### ISSUE TITLE
Invalid redeclaration of 'modelArray(from:anyType:)'

### ISSUE THREAD

**Issue by liubang0909** [kakaopensource/KakaJSON#12]
pod引入的 报这个错。。 求大神说下怎么调

**Comment by CoderMJLee** [comment]
之前的release包缓存了残余文件，按照下面步骤做就好了
- 删除项目底下Pods/KakaJSON文件夹
- 命令行`rm -rf ~/Library/Caches/CocoaPods/Pods/Release/KakaJSON`
- 最后重新`pod install`就好了

**Comment by liubang0909** [comment]
谢谢回复🙏  已经可以了
