### ISSUE TITLE
如果某一属性为空，强制让model转换失败的功能

### ISSUE THREAD

**Issue by mg459046365** [kakaopensource/KakaJSON#22]
类似于，如果某个对象有个id属性。需求是某一json数据中，如果该属性对应的字段没有值或者没有该属性对应的字段，则直接忽略其他属性的解析，直接强制让该model解析失败，抛出nil。

**Comment by CoderMJLee** [comment]
没有内置此类功能，你可以在转换完毕后自行去判断id是否有值即可

**Comment by mg459046365** [comment]
> 没有内置此类功能，你可以在转换完毕后自行去判断id是否有值即可

好的，谢谢回复。
