### ISSUE TITLE
 重构项目结构

### ISSUE THREAD

**Issue by luoxiu** [kakaopensource/KakaJSON#26]
现在的 KakaJSON 只有 cocoa touch framework 的 scheme，这会让在 macOS app 里使用 Carthage 添加依赖时会找不到对应 scheme 编译。（在 CocoaPods 下没有问题）

需要组织下项目结构：
——可以直接用 spm 重新生成支持多平台的 xcodeproj（建议）。
——也可以手动添加新的 macOS&tvOS schemes。

如果愿意的话我可以提交一个 pr~ 🍻

**Comment by CoderMJLee** [comment]
你这边可以提交一个哈，谢谢
