### ISSUE TITLE
使用了KaKaJSON还有必要使用swiftjson吗

### ISSUE THREAD

**Issue by lxlnihao** [kakaopensource/KakaJSON#29]
没有出KaKaJSON之前项目中使用了swiftjson,现在使用了KaKaJSON 和之前引入的swiftjson有冲突.请问我可以去掉swiftjson吗还是怎么处理,谢谢

**Comment by lxlnihao** [comment]
struct NetResponse<Element>: Convertible {
            let data: Element? = nil
            let msg: String = ""
            private(set) var code: Int = 0
        }
直接使用这个方法就可以了吗?

**Comment by CoderMJLee** [comment]
- 冲突在什么地方？
   - 目前KakaJSON用到的类型名称是有特地避开SwiftyJSON的
   - 你用的是最新版代码么？
   - SwiftyJSON和KakaJSON是可以一起使用的
- 第二份代码没看懂哈，是想表达什么呢？

**Comment by CoderMJLee** [comment]
再补充一点哈，如果你的项目中都是直接将服务器返回的JSON转成模型来用，不会直接用字典，是可以不使用SwiftyJSON的，但我认为用了SwiftyJSON会更方便

**Comment by mg459046365** [comment]
> 再补充一点哈，如果你的项目中都是直接将服务器返回的JSON转成模型来用，不会直接用字典，是可以不使用SwiftyJSON的，但我认为用了SwiftyJSON会更方便

目前我使用KaKaJSON都是直接将服务器返回的JSON数据转成模型用，感觉已经很方便了。不知道明杰老师说的用了SwiftyJSON会更方便，主要指的如何使用呢，能简单讲一下么，对我应该有帮助，非常想了解。

**Comment by CoderMJLee** [comment]
@mg459046365 就是在对JSON进行类型转换（as）、取值方面（JSON[key]）可以简化一点，不过也简化不了多少，毕竟稍微从JSON中取两下东西就转成模型了，后续都不会直接操作JSON了

**Comment by lxlnihao** [comment]
> * 冲突在什么地方？
>   
>   * 目前KakaJSON用到的类型名称是有特地避开SwiftyJSON的
>   * 你用的是最新版代码么？
>   * SwiftyJSON和KakaJSON是可以一起使用的
> * 第二份代码没看懂哈，是想表达什么呢？

第二份代码 不用看了没事
![11](https://user-images.githubusercontent.com/16555566/68283928-7595fb00-00b7-11ea-906b-22a4a6d84006.jpg)
![1573030864514](https://user-images.githubusercontent.com/16555566/68283959-834b8080-00b7-11ea-8da8-ee33916f9d3d.jpg)
![222](https://user-images.githubusercontent.com/16555566/68284163-e806db00-00b7-11ea-8d8a-a908ed1dfef2.jpg)
不知道别的小伙伴有没有遇到我这种问题,谢谢明杰老师

**Comment by lxlnihao** [comment]
补充一下 之前项目中有swiftjson 拖进去kakajson然后报出上面的问题 ,什么都没有改

**Comment by lxlnihao** [comment]
现在可以直接在项目中用kakajson 去掉swiftjson是没有问题的 只是想知道这种问题别人有没有遇到 为什么会出这个问题,看提示是起的名字冲突导致的

**Comment by mg459046365** [comment]
> @mg459046365 就是在对JSON进行类型转换（as）、取值方面（JSON[key]）可以简化一点，不过也简化不了多少，毕竟稍微从JSON中取两下东西就转成模型了，后续都不会直接操作JSON了

谢谢明杰老师啦，懂了

**Comment by CoderMJLee** [comment]
建议使用别的方式集成第三方库，这样可以模块化管理。不建议直接将库的代码拽入项目中
