### ISSUE TITLE
手动导入KaKaJSON库提示修改

### ISSUE THREAD

**Issue by lxlnihao** [kakaopensource/KakaJSON#30]
你好,我导入库之后提示我这个
![1572516939093](https://user-images.githubusercontent.com/16555566/67938526-a20acc80-fc0a-11e9-8869-49b32d8690cc.jpg)
可以根据提示改成叹号吗

**Comment by CoderMJLee** [comment]
你的环境是Xcode几？

**Comment by lxlnihao** [comment]
10.2.1  之前老项目用了swift写了几个功能,用的swiftjson保证字典安全, 模型用的是oc的代码,现在想把oc的模型代码改成swift 拖进去报这个,我自己新开的项目 写的demo没有问题 .只是拖到老项目里有问题
