### ISSUE TITLE
关于JSONObject 

### ISSUE THREAD

**Issue by MuRanJiangXia** [kakaopensource/KakaJSON#34]
我可以用 这个方法 把服务端的json 中id 转成struct 中的 userID
    func kj_modelKey(from property: Property) -> ModelPropertyKey {
        switch property.name {
        case "id": return "userID"
        default:
            return property.name
        }
    }

我怎么样在 转成字典时候 把 “userID” 转成 “ id” 时呢？

**Comment by CoderMJLee** [comment]
```swift
func kj_JSONKey(from property: Property) -> JSONPropertyKey
```
参考[【KakaJSON手册】06_Model转JSON](https://www.cnblogs.com/mjios/p/11370361.html#toc_title_7)

**Comment by MuRanJiangXia** [comment]
好的。
