### ISSUE TITLE
混编项目闪退

### ISSUE THREAD

**Issue by chenjiangui** [kakaopensource/KakaJSON#35]
model继承OC, 会闪退
![image](https://user-images.githubusercontent.com/18565140/69296366-a2fdaf80-0c46-11ea-8d9e-41380225d66d.png)
![image](https://user-images.githubusercontent.com/18565140/69297149-dc361f80-0c46-11ea-9022-4c6d7c9d77c6.png)

**Comment by shaop** [comment]
@CoderMJLee  目前似乎只对 OC 内的 `NSObject` 做了截断操作，其他继承自 `NSObject` 的子类没有处理，可以做是否 OC 类的判断吗？不行的话是否让外界提前告知有哪些需要规避掉的 OC 类

```swift
public struct Metadata {
    public static func type(_ type: Any.Type) -> BaseType? {
        ...
        let key = typeKey(type)
        if let mt = types[key] { return mt }
        
        // name
        let name = String(describing: type)
        if name == "Swift._SwiftObject"
            || name == "NSObject"
            || name == "_TtCs12_SwiftObject" { return nil }
```

**Comment by CoderMJLee** [comment]
可以给个Demo不

**Comment by chenjiangui** [comment]
@CoderMJLee 
[KakaJsonIssu.tar.gz](https://github.com/kakaopensource/KakaJSON/files/3919691/KakaJsonIssu.tar.gz)
Demo上传了

**Comment by CoderMJLee** [comment]
看了下Demo，找到问题所在了。KakaJSON目前是基于Swift的metadata进行解析的，OC的Model需要基于Runtime去解析，所以KakaJSON目前不支持纯OC的Model。如果你的Swift Model是直接继承NSObject，KakaJSON还是支持的。
目前的解决方案：使用基于Runtime的字典模型框架去解析OC的Model

**Comment by chenjiangui** [comment]
@CoderMJLee 这个解决方案是不行的, SwiftModel继承了OCModel, 但是有部分属性不是NSObject的属性, runtime解析不出来的. 现在主要是崩溃问题, 能避免继承自OC的model崩溃吗, 只转换能转换的属性

**Comment by pengshengsongcode** [comment]
> @CoderMJLee 这个解决方案是不行的, SwiftModel继承了OCModel, 但是有部分属性不是NSObject的属性, runtime解析不出来的. 现在主要是崩溃问题, 能避免继承自OC的model崩溃吗, 只转换能转换的属性

大佬 这个问题解决了么 我也遇到同样的问题了~
