### ISSUE TITLE
Error verifying ipa package

### ISSUE THREAD

**Issue by WGFcode** [kakaopensource/KakaJSON#38]
This bundle Payload/XXX.app/Frameworks/KakaJSON.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion\

**Comment by CoderMJLee** [comment]
问题解决了不？

**Comment by WGFcode** [comment]
解决了
