### ISSUE TITLE
This bundle Payload/JKYZF.app/Frameworks/KakaJSON.framework is invalid.

### ISSUE THREAD

**Issue by WGFcode** [kakaopensource/KakaJSON#43]
App Store Connect Operation Error：This bundle Payload/JKYZF.app/Frameworks/KakaJSON.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion

**Comment by CoderMJLee** [comment]
手动给它加个CFBundleVersion试试哈，参考：http://blog.sina.com.cn/s/blog_e88283710102wm4h.html

**Comment by WGFcode** [comment]
嗯嗯，之前也是在info.plist中添加了这个key解决的，但是每次更新库，有时候会忘记...所以希望后续能解决

**Comment by CoderMJLee** [comment]
好的
