### ISSUE TITLE
Swift Package Manager 依赖出错

### ISSUE THREAD

**Issue by mrqinshou** [kakaopensource/KakaJSON#44]
初学 iOS,在使用该库时,使用 SPM 添加依赖出错,看提示貌似是包含混合语言,日志如下,请问有人知道如何解吗,还望不吝赐教

Showing All Messages
/Users/mac/Library/Developer/Xcode/DerivedData/QSBoxIOS-gfcoshocdpymxrakohrtjsypvzrm/SourcePackages/checkouts/KakaJSON/Package.swift: target at '/Users/mac/Library/Developer/Xcode/DerivedData/QSBoxIOS-gfcoshocdpymxrakohrtjsypvzrm/SourcePackages/checkouts/KakaJSON/Tests/KakaJSONTests' contains mixed language source files; feature not supported

**Comment by kinarobin** [comment]
刚刚试了一下，可以正常使用。 你把`DerivedData`文件删除了重试看看。

![截屏2020-04-20下午12 59 06](https://user-images.githubusercontent.com/29303030/79715592-b94b8c80-8306-11ea-8cdd-dbccdcce4ec3.png)
