### ISSUE TITLE
真机运行报错

### ISSUE THREAD

**Issue by WGFcode** [kakaopensource/KakaJSON#45]
A shell task (/usr/bin/xcrun codesign --force --sign XXX --preserve-metadata=identifier,entitlements /Users/baicai/Library/Developer/Xcode/DerivedData/NXY-gctyqidlfcosnxdvubeulhljuelz/Build/Products/Debug-iphoneos/JKYZF.app/Frameworks/KakaJSON.framework) failed with exit code 1:
/Users/baicai/Library/Developer/Xcode/DerivedData/NXY-gctyqidlfcosnxdvubeulhljuelz/Build/Products/Debug-iphoneos/JKYZF.app/Frameworks/KakaJSON.framework: resource fork, Finder information, or similar detritus not allowed

Command /bin/sh failed with exit code 1

**Comment by CoderMJLee** [comment]
参考看看：https://blog.csdn.net/jia12216/article/details/70652777，
