### ISSUE TITLE
pod error

### ISSUE THREAD

**Issue by ls19491314** [kakaopensource/KakaJSON#5]
<img width="500" alt="WeChat65c7127eeff19a3172871501c321d527" src="https://user-images.githubusercontent.com/12245278/63081089-4c147a00-bf75-11e9-946e-322ac5691122.png">
mj大神终于出新啦，赶紧过来尝试，就是为啥pod 后报错呢

**Comment by jtyXcode** [comment]
Xcode 11 beta 2 语法报错
![Image to JTY](http://chuantu.xyz/t6/702/1565856747x992245926.jpg)
![Image to JTY](http://chuantu.xyz/t6/702/1565856901x977013264.jpg)

**Comment by ls19491314** [comment]
我Xcode Version 10.2.1 报错

**Comment by CoderMJLee** [comment]
不好意思，因为我之前基于Xcode11编写的。刚才兼容了一下Xcode10，麻烦重新pod一下1.0.3版本哈

**Comment by ls19491314** [comment]
en，thanks mj
